services:
  python:
    image: python:3.10-slim
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
    tty: true
    volumes:
      - ./:/workspace
    working_dir: /workspace
    restart: always

  pypy:
    image: pypy:3.10-slim
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
    tty: true
    volumes:
      - ./:/workspace
    working_dir: /workspace
    restart: always

  rust:
    image: rust:1.70
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
    tty: true
    volumes:
      - ./:/workspace
    working_dir: /workspace
    restart: always